package main

type commands struct {
	Name          string
	Install       string
	Uninstall     string
	Upgrade       string
	Search        string
	Info          string
	UpgradeAll    string
	ListInstalled string
	UpdateIndex   string
}

var pm_commands = map[string]commands{
	"i": {
		Name:          "i",
		Install:       "i install x",
		Uninstall:     "i uninstall x",
		Upgrade:       "i upgrade x",
		Search:        "i search x",
		Info:          "i info x",
		UpgradeAll:    "i upgrade",
		ListInstalled: "i list",
	},
	"apt": { // needs sudo for install, remove, upgrade, update
		Name:          "apt",
		Install:       "sudo apt install x",
		Uninstall:     "sudo apt remove x",
		Upgrade:       "sudo apt install --only-upgrade x",
		Search:        "apt search x",
		Info:          "apt show x",
		UpgradeAll:    "sudo apt upgrade",
		ListInstalled: "apt list --installed", // apt list -i
		UpdateIndex:   "sudo apt update",
	},
	"brew": { // no need for sudo AT ALL
		Name:          "brew",
		Install:       "brew install x",
		Uninstall:     "brew uninstall x",
		Upgrade:       "brew upgrade x",
		Search:        "brew search x",
		Info:          "brew info x",
		UpgradeAll:    "brew upgrade",
		ListInstalled: "brew list",
		UpdateIndex:   "brew update",
	},
	"port": { // needs sudo for install, remove, upgrade, update
		Name:          "port",
		Install:       "sudo port install x",
		Uninstall:     "sudo port uninstall x",
		Upgrade:       "sudo port upgrade x",
		Search:        "port search x",
		Info:          "port info x",
		UpgradeAll:    "sudo port upgrade",
		ListInstalled: "port installed",
	},
	"flatpak": { // if system-wide, need sudo for install, remove, upgrade, update
		Name:          "flatpak",
		Install:       "sudo flatpak install x",
		Uninstall:     "sudo flatpak uninstall x",
		Upgrade:       "sudo flatpak update x",
		Search:        "flatpak search x",
		Info:          "flatpak info x",
		UpgradeAll:    "sudo flatpak update",
		ListInstalled: "flatpak list --app", // added --app to show apps only
	},
	"snap": { // need sudo for install, remove, upgrade, update
		Name:          "snap",
		Install:       "sudo snap install --classic x", // --classic or not ?
		Uninstall:     "sudo snap remove x",
		Upgrade:       "sudo snap refresh x",
		Search:        "snap find x",
		Info:          "snap info x",
		UpgradeAll:    "sudo snap refresh",
		ListInstalled: "snap list",
	},
	"dnf": { // need sudo for install, remove, upgrade, update
		Name:          "dnf",
		Install:       "sudo dnf install -y x",
		Uninstall:     "sudo dnf remove -y x",
		Upgrade:       "sudo dnf upgrade -y x",
		Search:        "dnf search x",
		Info:          "dnf info x",
		UpgradeAll:    "sudo dnf upgrade -y",
		ListInstalled: "dnf list installed",
		UpdateIndex:   "dnf check-update",
	},
	"rpm": { // need sudo for install, remove, upgrade, update
		Name:          "rpm",
		Install:       "sudo rpm -i x",
		Uninstall:     "sudo rpm -e x",
		Upgrade:       "sudo rpm -U x",
		Search:        "rpm -q x",
		Info:          "rpm -q x",
		UpgradeAll:    "sudo rpm -Uvh x",
		ListInstalled: "rpm -qa",
	},
	"pacman": { // need sudo for install, remove, upgrade, update
		Name:          "pacman",
		Install:       "sudo pacman -S --noconfirm x",
		Uninstall:     "sudo pacman -Rs --noconfirm x",
		Upgrade:       "sudo pacman -Syu --noconfirm x", // Upgrade specific pkg and system? Usually just -S to reinstall/upgrade specific
		Search:        "pacman -Ss x",
		Info:          "pacman -Qi x",
		UpgradeAll:    "sudo pacman -Syu --noconfirm",
		ListInstalled: "pacman -Q",
		UpdateIndex:   "sudo pacman -Sy",
	},
	"yum": { // need sudo for install, remove, upgrade, update
		Name:          "yum",
		Install:       "sudo yum install -y x",
		Uninstall:     "sudo yum remove -y x",
		Upgrade:       "sudo yum update -y x",
		Search:        "yum search x",
		Info:          "yum info x",
		UpgradeAll:    "sudo yum update -y",
		ListInstalled: "yum list installed",
		UpdateIndex:   "sudo yum makecache",
	},
	"zypper": { // needs sudo for install, remove, upgrade, update
		Name:          "zypper",
		Install:       "sudo zypper install -n x",
		Uninstall:     "sudo zypper remove -n x",
		Upgrade:       "sudo zypper update -n x",
		Search:        "zypper search x",
		Info:          "zypper info x",
		UpgradeAll:    "sudo zypper update -n",
		ListInstalled: "zypper se --installed-only",
		UpdateIndex:   "sudo zypper refresh",
	},
	"apk": { // needs sudo for install, remove, upgrade, update
		Name:          "apk",
		Install:       "sudo apk add x",
		Uninstall:     "sudo apk del x",
		Upgrade:       "sudo apk add --upgrade x",
		Search:        "apk search x",
		Info:          "apk info x",
		UpgradeAll:    "sudo apk upgrade",
		ListInstalled: "apk info",
		UpdateIndex:   "sudo apk update",
	},
	"xbps": { // needs sudo for install, remove, upgrade, update
		Name:          "xbps",
		Install:       "sudo xbps-install -y x",
		Uninstall:     "sudo xbps-remove -y x",
		Upgrade:       "sudo xbps-install -u x",
		Search:        "xbps-query -Rs x",
		Info:          "xbps-query -R x", // Remote info? or local -f? assuming remote
		UpgradeAll:    "sudo xbps-install -Suy",
		ListInstalled: "xbps-query -l",
		UpdateIndex:   "sudo xbps-install -S",
	},
	"emerge": { // needs sudo for install, remove, upgrade, update
		Name:          "emerge",
		Install:       "sudo emerge x",
		Uninstall:     "sudo emerge -C x",
		Upgrade:       "sudo emerge -u x",
		Search:        "emerge -s x",
		Info:          "emerge -S x",
		UpgradeAll:    "sudo emerge -uDN @world",
		ListInstalled: "qlist -I", // needs portage-utils potentially
		UpdateIndex:   "sudo emerge --sync",
	},
	"nix-env": { // no need for sudo
		Name:          "nix-env",
		Install:       "nix-env -iA nixpkgs.x",
		Uninstall:     "nix-env -e x",
		Upgrade:       "nix-env -u x",
		Search:        "nix-env -qaP x",
		Info:          "nix-env -qa --description x",
		UpgradeAll:    "nix-env -u",
		ListInstalled: "nix-env -q",
		UpdateIndex:   "nix-channel --update", // or nix-env -u without args? usually channel update is needed
	},
	"pkg": { // needs sudo for install, remove, upgrade, update
		Name:          "pkg",
		Install:       "sudo pkg install -y x",
		Uninstall:     "sudo pkg delete -y x",
		Upgrade:       "sudo pkg upgrade -y x",
		Search:        "pkg search x",
		Info:          "pkg info x",
		UpgradeAll:    "sudo pkg upgrade -y",
		ListInstalled: "pkg info",
	},
	"winget": { // no need for 'administrator privileges' as MS Windows shows a popup if it needs
		Name:          "winget",
		Install:       "winget install x",
		Uninstall:     "winget uninstall x",
		Upgrade:       "winget upgrade x",
		Search:        "winget search x",
		Info:          "winget show x",
		UpgradeAll:    "winget upgrade",
		ListInstalled: "winget list",
	},
	"scoop": { // no need for 'administrator privileges'
		Name:          "scoop",
		Install:       "scoop install x",
		Uninstall:     "scoop uninstall x",
		Upgrade:       "scoop update x",
		Search:        "scoop search x",
		Info:          "scoop info x",
		UpgradeAll:    "scoop update",
		ListInstalled: "scoop list",
	},
	"choco": { // no need for 'administrator privileges' as MS Windows shows a popup if it needs
		Name:          "choco",
		Install:       "choco install x",
		Uninstall:     "choco uninstall x",
		Upgrade:       "choco upgrade x",
		Search:        "choco search x",
		Info:          "choco info x",
		UpgradeAll:    "choco upgrade",
		ListInstalled: "choco list",
	},
	"urpm": { // needs sudo for urpmi, urpme
		Name:          "urpm",
		Install:       "sudo urpmi x",
		Uninstall:     "sudo urpme x",
		Upgrade:       "sudo urpmi --update x",
		Search:        "urpmq --search x",
		Info:          "urpmq --info x",
		UpgradeAll:    "sudo urpmi --update",
		ListInstalled: "urpmq --list",
	},
	"slackpkg": { // requires sudo for install, remove, upgrade, update
		Name:          "slackpkg",
		Install:       "sudo slackpkg install x",
		Uninstall:     "sudo slackpkg remove x",
		Upgrade:       "sudo slackpkg upgrade x",
		Search:        "slackpkg search x",
		Info:          "slackpkg info x",
		UpgradeAll:    "sudo slackpkg upgrade",
		ListInstalled: "slackpkg list installed",
	},
	"prt-get": { // requires sudo for install, remove, upgrade, update
		Name:          "prt-get",
		Install:       "sudo prt-get install x",
		Uninstall:     "sudo prt-get remove x",
		Upgrade:       "sudo prt-get upgrade x",
		Search:        "prt-get search x",
		Info:          "prt-get info x",
		UpgradeAll:    "sudo prt-get upgrade",
		ListInstalled: "prt-get list installed",
	},
	"pkgman": { // no need for sudo
		Name:          "pkgman",
		Install:       "pkgman -S x",
		Uninstall:     "pkgman -R x",
		Upgrade:       "pkgman -Syu x",
		Search:        "pkgman -Ss x",
		Info:          "pkgman -Qi x",
		UpgradeAll:    "pkgman -Syu",
		ListInstalled: "pkgman -Q",
	},
	"opkg": { // requires sudo for install, remove, upgrade, update
		Name:          "opkg",
		Install:       "sudo opkg install x",
		Uninstall:     "sudo opkg remove x",
		Upgrade:       "sudo opkg upgrade x",
		Search:        "opkg search x",
		Info:          "opkg info x",
		UpgradeAll:    "sudo opkg upgrade",
		ListInstalled: "opkg list-installed",
	},
	"eopkg": { // requires sudo for install, remove, upgrade, update
		Name:          "eopkg",
		Install:       "sudo eopkg install x",
		Uninstall:     "sudo eopkg remove x",
		Upgrade:       "sudo eopkg upgrade x",
		Search:        "eopkg search x",
		Info:          "eopkg info x",
		UpgradeAll:    "sudo eopkg upgrade",
		ListInstalled: "eopkg list-installed",
	},
	"guix": { // no need for sudo
		Name:          "guix",
		Install:       "guix install x",
		Uninstall:     "guix remove x",
		Upgrade:       "guix upgrade x",
		Search:        "guix search x",
		Info:          "guix info x",
		UpgradeAll:    "guix upgrade",
		ListInstalled: "guix list",
	},
	"cards": { // requires sudo for install, remove, upgrade, update
		Name:          "cards",
		Install:       "sudo cards install x",
		Uninstall:     "sudo cards remove x",
		Upgrade:       "sudo cards upgrade x",
		Search:        "cards search x",
		Info:          "cards info x",
		UpgradeAll:    "sudo cards upgrade",
		ListInstalled: "cards list",
	},
}
